[WIP] First commit for tvm-conv2d benchmark code
buddy-compiler/buddy-mlir pull request #1
Opened 2021-08-06 14:07 UTC by Joejiong

This is the first commit for tvm-conv2d benchmark code:
Modification including the following two files:
- readme.md
- tvm-conv2d.py

2021-08-31 02:10 UTC, zhanghb97 requested changes
Good! But there are some details that should be fixed, and I have left comments.

2021-08-31 02:10 UTC, zhanghb97 commented on examples/conv-opt/comparison/README.md
> +$ python3 tvm-conv2d.py 3
```
$ python3 tvm-conv2d.py 3
usage: tvm-conv2d.py [-h] [--size N]
tvm-conv2d.py: error: unrecognized arguments: 3
```

It seems that the command should be:

```
python3 tvm-conv2d.py --size 3
```

2021-08-31 11:48 UTC, Joejiong commented on examples/conv-opt/comparison/tvm-conv2d.py
> +TILED_HEIGHT, TILED_WEIGHT = 3, 3  # Tile sizes for height and weight
Actually the tile-size is taken from their(TVM) tutorial, but it really should be decided by brute-force-like auto-search module, here I manual tried some configurations find the default one is better.

2021-08-31 12:09 UTC, Joejiong commented on examples/conv-opt/comparison/README.md
> +$ python3 tvm-conv2d.py 3
right, done

2021-08-31 12:10 UTC, Joejiong commented on examples/conv-opt/comparison/tvm-conv2d.py
> +
done

2021-08-31 12:10 UTC, Joejiong commented on examples/conv-opt/comparison/tvm-conv2d.py
> +
done

2021-08-31 12:10 UTC, Joejiong commented on examples/conv-opt/comparison/tvm-conv2d.py
> +
done

2021-08-31 13:16 UTC, Joejiong commented on examples/conv-opt/comparison/tvm-conv2d.py
> +TARGET = 'llvm -mcpu=skylake-avx512'
sure, done

2021-08-31 13:17 UTC, Joejiong commented on examples/conv-opt/comparison/tvm-conv2d.py
> +
done

2021-08-31 15:26 UTC, zhanghb97 approved these changes
Thanks! Remember to add a new line to the end of the file for the next time.

2021-08-31 15:28 UTC, merged

2021-09-01 07:20 UTC, Joejiong commented
> Thanks! Remember to add a new line to the end of the file for the next time.

Thanks, ok