[examples][MLIRVector] improve vector dialect examples for memory access
buddy-compiler/buddy-mlir pull request #107
Opened 2023-01-27 10:58 UTC by Origami404

add or improve examples for memory access related operations in vector dialect, including:

- load/store
- expandload/compressstore
- maskedload/maskedstore
- gather/scatter

also do a rename to match operation name better:

- `expand-load` => `expandload`

This PR is a small and finished part of WIP PR #90 .

2023-02-12 15:20 UTC, zhanghb97 requested changes

2023-02-12 15:20 UTC, zhanghb97 commented on examples/MLIRVector/vector-expandload.mlir
> +  // expandload require a pass through value at any time
require -> requires

2023-02-12 15:20 UTC, zhanghb97 commented on examples/MLIRVector/vector-expandload.mlir
> +  // because position 1 is masked off, so it will not move to load next element
Remove "because".

2023-02-12 15:20 UTC, zhanghb97 commented on examples/MLIRVector/vector-expandload.mlir
> +  // In this case, it will behavior like the memref is flat
behavior -> behave

2023-02-12 15:20 UTC, zhanghb97 commented on examples/MLIRVector/vector-expandload.mlir
> +  // it behavior likes vector.load -- it's a platform-specified operation
behavior -> behaves

platform-specified -> platform-specific

2023-02-12 15:20 UTC, zhanghb97 commented on examples/MLIRVector/vector-gather.mlir
> +  // vector.gather is also load with mask, but loading element in custom order,
vector.gather also loads with a mask, but it loads elements in a custom order,

2023-02-12 15:20 UTC, zhanghb97 commented on examples/MLIRVector/vector-gather.mlir
> +  // As a comparison, that's what vector.maskedload doing:
doing -> does

2023-02-12 15:20 UTC, zhanghb97 commented on examples/MLIRVector/vector-gather.mlir
> +  // But vector.gather support loading n-D vector.
support -> supports

2023-02-12 15:20 UTC, zhanghb97 commented on examples/MLIRVector/vector-load.mlir
> +  // In this case, it will behavior like the memref is "flat"
behavior -> behave

2023-02-12 15:20 UTC, zhanghb97 commented on examples/MLIRVector/vector-maskedload.mlir
> +  // maskedload is load with mask, supporting to load 1-D vector into n-D memref with mask.
is load -> loads

2023-02-12 15:20 UTC, zhanghb97 commented on examples/MLIRVector/vector-maskedload.mlir
> +  // maskedload require a pass through value at any time
requires

2023-02-12 15:20 UTC, zhanghb97 commented on examples/MLIRVector/vector-maskedload.mlir
> +  // In this case, it will behavior like the memref is flat
behavior -> behave

2023-02-12 15:20 UTC, zhanghb97 commented on examples/MLIRVector/vector-maskedload.mlir
> +  // it behavior likes vector.load -- it's a platform-specified operation
behavior -> behaves
platform-specified -> platform-specific

2023-02-12 15:20 UTC, zhanghb97 commented on examples/MLIRVector/vector-maskedstore.mlir
> +  // maskedstore is store with mask, supporting store 1-D vector into n-D memref with mask.
is store -> stores

2023-02-12 15:20 UTC, zhanghb97 commented on examples/MLIRVector/vector-maskedstore.mlir
> +  // In this case, it will behavior like the memref is flat
behavior -> behave

2023-02-12 15:20 UTC, zhanghb97 commented on examples/MLIRVector/vector-maskedstore.mlir
> +  // Tips: because keep using same memory region for all examples will make the
Remove "because"

2023-02-12 15:20 UTC, zhanghb97 commented on examples/MLIRVector/vector-maskedstore.mlir
> +  //    case 2: what will happened if we store into somewhere out of bound?
happened -> happen

2023-02-12 15:20 UTC, zhanghb97 commented on examples/MLIRVector/vector-scatter.mlir
> +  // vector.scatter is also store with mask, but storing element in custom order,
vector.scatter also stores with mask, but it stores elements in a custom order,

2023-02-12 15:20 UTC, zhanghb97 commented on examples/MLIRVector/vector-store.mlir
> +  // In this case, it will behavior like the memref is flat
behavior -> behave

2023-02-12 15:20 UTC, zhanghb97 commented on examples/MLIRVector/vector-store.mlir
> +  // Tips: because keep using same memory region for all examples will make the
Remove "because"

2023-02-12 15:20 UTC, zhanghb97 commented on examples/MLIRVector/makefile
> +		-shared-libs=${MLIR_RUNNER_UTILS} -shared-libs=${MLIR_C_RUNNER_UTILS}
As the warning here, please add a newline at the end of the file.

2023-02-12 15:20 UTC, zhanghb97 commented on examples/MLIRVector/vector-store.mlir
> +}
As the warning here, please add a newline at the end of the file.

2023-04-07 14:41 UTC, Origami404 commented
Rebased onto main and fixed syntax errors mentioned here (and more by grammarly)

2023-04-19 06:01 UTC, merged