[buddy-lsp-server] add buddy-lsp-server
buddy-compiler/buddy-mlir pull request #128
Opened 2023-03-24 13:09 UTC by Origami404

Having an LSP server is very handy when writing MLIR files. This PR builds an lsp server that supports the new dialect by adding Buddy-MLIR's new dialect directly to the registry.

In theory this program should be a drop-in replacement for mlir-lsp-server. Meaning you should be able to directly modify VSCode settings (or similar settings for other editors) to:

```json
{
    "mlir.server_path": "YOUR_BUDDY_MLIR_BUILD/bin/buddy-lsp-server",
}
```

After modification, your editor should have correct completion and error prompts for new dialects such as `rvv`.

2023-03-24 13:15 UTC, Origami404 commented
After #123 be merged, support for Gemini dialect needs to be added into this too.

2023-03-31 10:47 UTC, zhanghb97 requested changes
Cool! How about adding the how-to guide to the README?

2023-03-31 10:47 UTC, zhanghb97 commented on tools/buddy-lsp-server/CMakeLists.txt
> +)
Please add an empty line here.

2023-03-31 10:47 UTC, zhanghb97 commented on tools/buddy-lsp-server/buddy-lsp-server.cpp
> +  registry.insert<buddy::bud::BudDialect,
Please add the Gemmini dialect here.

2023-04-07 12:02 UTC, Origami404 commented
Rebased onto main and added instructions to README.

2023-05-25 07:23 UTC, merged