[Examples][TOSA] Bug in TOSA examples
buddy-compiler/buddy-mlir pull request #155
Opened 2023-06-04 11:15 UTC by Ris-Bali

The PR aims to solve two bugs in TOSA examples
1) The pass pipeline bug
2) The bug in tosa.resizeOp

2023-06-05 04:12 UTC, meshtag commented
Please describe the bugs in detail and/or file a issue for them. This would help us understand the intent and the solution itself.

2023-06-13 21:10 UTC, Ris-Bali commented
I have solved the bugs. Pls review

2023-06-16 16:26 UTC, meshtag requested changes
One minor comment, rest LGTM :)

2023-06-16 16:26 UTC, meshtag commented on examples/MLIRTOSA/tosa-resize.mlir
> +    scale = array<i64 : 4, 2, 4, 2>, offset = array<i64 : 0, 0>,
```suggestion
    scale = array<i64 : 4, 2, 4, 2>, output_size = [4, 4], stride = [0, 0], offset = array<i64 : 0, 0>,
    stride_fp = [0.5 : f32, 0.5 : f32], offset_fp = [0.1 : f32, 0.2 : f32], shift = 0 : i32,
    mode = "NEAREST_NEIGHBOR", border = array<i64 : 0, 0>} : (tensor<1x2x2x1xf32>)  -> (tensor<1x4x4x1xf32>)
```

2023-06-16 16:27 UTC, meshtag commented on examples/MLIRTOSA/makefile
> +		-shared-libs=${MLIR_RUNNER_UTILS} -shared-libs=${MLIR_C_RUNNER_UTILS}
```suggestion
		-shared-libs=${MLIR_RUNNER_UTILS} -shared-libs=${MLIR_C_RUNNER_UTILS}
```

2023-06-16 19:16 UTC, meshtag commented on examples/MLIRTOSA/tosa-resize.mlir
> +    scale = array<i64 : 4, 2, 4, 2>, offset = array<i64 : 0, 0>,
Please add `stride_fp`, `offset_fp` and `shift`

2023-06-16 19:50 UTC, meshtag approved these changes

2023-06-21 15:44 UTC, Ris-Bali commented
@zhanghb97  Can we land this PR ? Please do let me know if I need to make any changes in the PR. Thanks

2023-07-12 16:01 UTC, zhanghb97 commented
Sorry for the late reply!
Nice fix! Thanks! @Ris-Bali @meshtag

2023-07-12 16:01 UTC, merged