[midend][tests] Add broadcast BatchMatMul optimization pass and tests.
buddy-compiler/buddy-mlir pull request #187
Opened 2023-08-19 08:20 UTC by EllisLambda

2023-08-19 15:34 UTC, xlinsist requested changes

2023-08-19 15:34 UTC, xlinsist commented on midend/lib/Conversion/MatMulOptimization/BatchMatMulOptimize.cpp
> +//-------------------------------------------------===//
Please reformat the title comment for neatness.

2023-08-19 15:55 UTC, xlinsist requested changes

2023-08-19 15:55 UTC, xlinsist commented on midend/lib/Conversion/MatMulOptimization/BatchMatMulOptimize.cpp
> +    // build loop body
Please make sure the comments are decent(i.e. capitalized and expressed formally). You should also double-check the other comments in this PR.

2023-08-19 15:55 UTC, xlinsist commented on examples/MLIRLinalg/linalg-batch-matmul.mlir
> +}
Add a space at the end of the line.

2023-08-19 15:55 UTC, xlinsist commented on examples/MLIRLinalg/makefile
> +linalg-batch-matmul-optimize-run:
In line 194, `linalg-batch-matmul-optimize-run` is redundant with line 137 and should be removed.

2023-08-19 15:55 UTC, xlinsist commented on examples/MLIRLinalg/makefile
> +		-batchmatmul-optimize="step-placeholder=64" \
It is recommanded to use `vector-size` instead of  `step-placeholder` since it is easyer to understand.

2023-08-19 16:15 UTC, xlinsist commented
Thanks! @EllisLambda I have left some suggestions to make it better, and I think these are enough for this PR. More verifications in real scenarios(e.g. simultaneously process `linalg.batch_matmul` of multiple sizes) may be needed in the future.

@zhanghb97 you may also see https://github.com/buddy-compiler/buddy-benchmark/pull/73.

2023-08-20 15:34 UTC, xlinsist commented
> @EllisLambda Why add batch_matmul pass to opt? I think it is inappropriate to add a certain op pass in opt.

`batch_matmul` is a typical opertion which is widely used in transformer models, so I think it is reasonable to provide a tailor-made pass for it.

Nevertheless, it would be better if `matmul-optimize` pass can incorporate the lowering optimizations of both `linalg.matmul` and `linalg.batch_matmul`. WDYT @EllisLambda ?

2023-08-20 15:44 UTC, linuxlonelyeagle commented
In fact, there is some truth to this, but I think this PR should explain what optimizations have been made? Where has the optimization been made?

2023-08-20 16:33 UTC, EllisLambda commented
> In fact, there is some truth to this, but I think this PR should explain what optimizations have been made? Where has the optimization been made?

I tried to 

> WDYT

The optimization styles between Matmul and BatchMatmul are quite distinct. On different hardware, the performance of these two operations may differ. Separating might be better?

2023-08-20 16:34 UTC, EllisLambda commented
> In fact, there is some truth to this, but I think this PR should explain what optimizations have been made? Where has the optimization been made?



> > @EllisLambda Why add batch_matmul pass to opt? I think it is inappropriate to add a certain op pass in opt.
> 
> `batch_matmul` is a typical opertion which is widely used in transformer models, so I think it is reasonable to provide a tailor-made pass for it.
> 
> Nevertheless, it would be better if `matmul-optimize` pass can incorporate the lowering optimizations of both `linalg.matmul` and `linalg.batch_matmul`. WDYT @EllisLambda ?

The optimization styles between Matmul and BatchMatmul are quite distinct. On different hardware, the performance of these two operations may differ. Separating might be better?

2023-08-20 16:35 UTC, EllisLambda commented
> In fact, there is some truth to this, but I think this PR should explain what optimizations have been made? Where has the optimization been made?

Ok, I will add the explanation.

2023-08-26 05:12 UTC, xlinsist commented
> Separating might be better? 
Yes, we decide to develop `batchmatmul-optimize` pass specifically for `linalg.batch_matmul` right now.

Yumin@EllisLambda , about the "bug" you mention in your description, we can unify the support of floating point and integer with another interface. If not, starting a new discussion about integer operations would be more appropriate so that the relevant comments in your description could be removed, as this PR just needs to take floating point operations into account.

2023-08-29 03:39 UTC, EllisLambda commented
> > Separating might be better?
> 
> Yes, we decide to develop `batchmatmul-optimize` pass specifically for `linalg.batch_matmul` right now.
> 
> Yumin @EllisLambda , about the "bug" you mention in your description, we can unify the support of floating point and integer with another interface. If not, starting a new discussion about integer operations would be more appropriate so that the relevant comments in your description could be removed, as this PR just needs to take floating point operations into account.

Ok! I see.

2023-09-08 15:58 UTC, EllisLambda commented
@xlinsist I have amended my PR.

2023-09-09 06:02 UTC, merged