add BuddyConvolution
buddy-compiler/buddy-mlir pull request #333
Opened 2024-06-17 13:35 UTC by FloatingcloudKnight

2024-06-17 17:46 UTC, zhanghb97 requested changes

2024-06-17 17:46 UTC, zhanghb97 commented on examples/BuddyConvolution/.gitignore
> +log.s
Please add an empty line here.

2024-06-17 17:46 UTC, zhanghb97 commented on examples/BuddyConvolution/makefile
> +		-shared-libs=${MLIR_RUNNER_UTILS} -shared-libs=${MLIR_C_RUNNER_UTILS}
Please add an empty line here.

2024-06-17 17:46 UTC, zhanghb97 commented on examples/BuddyConvolution/conv2d.mlir
> +}
Please add an empty line here.

2024-06-17 17:46 UTC, zhanghb97 commented on examples/BuddyConvolution/CMakeLists.txt
Please remove this file.

2024-06-17 17:46 UTC, zhanghb97 commented on examples/BuddyConvolution/makefile
> +test-lower:
Please remove this target.

2024-06-17 17:46 UTC, zhanghb97 commented on examples/BuddyConvolution/conv2d.mlir
Please add the test.
If you run the `ninja check-buddy`, you will get the failed report.
See [here](https://github.com/buddy-compiler/buddy-mlir/commit/768f1f7722c36608cd036b293c95ad1c2fa2d5d0#diff-fcc233b7c6e44b034e04750a4a53afa906effad5c30d6a41704075ba73bd32cf) as an example.

2024-06-18 04:53 UTC, FloatingcloudKnight reviewed
update BuddyConvolution

2024-06-18 09:32 UTC, zhanghb97 approved these changes
Good first step! Thanks!

2024-06-18 10:33 UTC, merged