Vector Dialect Examples
buddy-compiler/buddy-mlir pull request #38
Opened 2022-06-02 17:59 UTC by Ris-Bali

Examples for operations in vector dialect .

2022-06-05 12:14 UTC, Ris-Bali commented
Done ! Pls Review

2022-06-06 20:43 UTC, meshtag commented
Please ping me one you are done adding all examples you want to, I'll start the review process then.

2022-06-07 00:23 UTC, Ris-Bali commented
@meshtag I'm done with all the examples please review

2022-06-07 06:02 UTC, meshtag commented
I had a look at the code, a generic suggestion from my side for making variable naming more obvious is : 
 - Use %cons1 to represent a constant with value 1 (not any other value)
 - Please take care of minor formatting issues as well (space after comma, newline at the end of each file etc.)
 
 I'll try to provide a more detailed review and test the code once I get some time.

2022-06-07 18:12 UTC, Ris-Bali commented
I think I have addressed the formatting errors pls review

2022-06-08 19:27 UTC, meshtag requested changes
I have added a commit addressing whitespace issues. Please go through it carefully and check if any other similar issues are to be addressed.

2022-06-08 19:27 UTC, meshtag commented on examples/MLIRVector/vector-maskedstore.mlir
> +  %c1 = arith.constant 2 : index
This does not follows the name convention, please rectify it.

2022-06-09 06:49 UTC, Ris-Bali commented
@meshtag I have addressed all your formatting isuues please review

2022-06-09 20:04 UTC, merged