[Midend] Add RFFT op in Extend DAP Pass
buddy-compiler/buddy-mlir pull request #387
Opened 2024-09-15 15:34 UTC by BrokenArrow1404

Add RFFT op to calc FFT for the real number. Algorithm from [PocketFFT ](https://gitlab.mpcdf.mpg.de/mtr/pocketfft/-/blob/master/pocketfft.c?ref_type=heads)library.

2024-10-11 16:03 UTC, taiqzheng requested changes

2024-10-11 16:20 UTC, taiqzheng requested changes

2024-10-11 16:20 UTC, taiqzheng commented on examples/DAPDialect/CMakeLists.txt
> +)
Please add an empty line at the end.

2024-10-13 17:34 UTC, taiqzheng commented on examples/DAPDialect/CMakeLists.txt
> +add_executable(buddy-whisper-preprocess-rfft WhisperPreprocessRFFT.cpp)
please change target `buddy-whisper-preprocess-rfft` to `buddy-rfft`, for it is a standalone operator.

2024-10-13 17:35 UTC, taiqzheng commented on frontend/Interfaces/buddy/DAP/DSP/WhisperPreprocess.h
> +
please remove two empty lines here.

2024-10-13 17:36 UTC, taiqzheng commented on frontend/Interfaces/lib/DAP-extend.mlir
> +  // return %in : memref<400xf64>
please remove the comment(line 7).

2024-10-13 17:40 UTC, taiqzheng commented on examples/DAPDialect/WhisperPreprocessRFFT.cpp
> +
please remove the empty line before `dap::RFFT`

2024-10-13 17:42 UTC, taiqzheng commented on examples/DAPDialect/README.md
> +
Please remove line 8~ line 66, if `buddy-rfft` doesn't need python binding.

2024-10-15 06:22 UTC, taiqzheng commented on examples/DAPDialect/RFFT.cpp
> +//===- WhisperPreprocessor.cpp --------------------------------------------===//
`//===- WhisperPreprocessor.cpp --------------------------------------------===//`change to
`//===- RFFT.cpp - Example of DAP RFFT -------------------------------------===//`

2024-10-15 11:51 UTC, taiqzheng commented on frontend/Interfaces/buddy/DAP/DSP/WhisperPreprocess.h
> +
line 55: `// Function for RFFT`

2024-10-15 14:13 UTC, taiqzheng approved these changes
LGTM. Thanks!

2024-10-22 03:28 UTC, zhanghb97 approved these changes
Thanks!
Please add more `rfft` operation tests in your next PR!

2024-10-22 03:28 UTC, merged