[OSPP] Morphological Transformations
buddy-compiler/buddy-mlir pull request #82
Opened 2022-10-28 10:31 UTC by Ris-Bali

The PR aims to implement morphological transformations. A PR for #70.

2022-10-28 12:39 UTC, meshtag requested changes
Next review iteration.

2022-10-28 12:39 UTC, meshtag commented on include/Utils/DIPUtils.h
> +
Remove this space.

2022-10-28 12:51 UTC, Ris-Bali commented on include/Utils/DIPUtils.h
> +                Value tailCond =
Yes there is no need for this condition.

2022-10-28 13:17 UTC, meshtag commented
I do not think we require tests with multiple type inputs/outputs for these operations, the type handling infrastructure is same across all operations in the dialect and hence can be verified with type specific tests only for `correlation_2d` op. Having them for all other operations as well feels like a lot of avoidable code duplication to me.

2022-10-28 17:57 UTC, meshtag commented on docs/dip-opt.md
> +Boundary extrapolation can be done using
No need to copy paste this for each and every op in morphological operations category. 

Create a separate section for morphological operations and then explain each operation in respective subsections.

2022-10-30 09:45 UTC, meshtag commented
Ping me once you fix the issue with examples

2022-10-30 15:25 UTC, meshtag approved these changes

2022-10-30 15:25 UTC, merged